name: env_s
channels:
        - conda-forge
        - defaults
dependencies:
        - python=3.10.6
        - h5py
        - notebook
        - pip
        - pip:
                - Pillow==9.5.0
                - --extra-index-url https://download.pytorch.org/whl/cu113
                - torch==1.12.1+cu113
                - torchvision==0.13.1+cu113
                - tensorboard
                - pytorch-lightning==1.9.0
                - lightning==1.9.0
                - fastmri
                - matplotlib
